<?php

namespace ContainerKd0FgX3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecruteurService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.DsvvdXF.App\Entity\Recruteur' shared service.
     *
     * @return \App\Entity\Recruteur
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.DsvvdXF": it references class "App\\Entity\\Recruteur" but no such service exists.');
    }
}
