<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZakWY5x\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZakWY5x/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerZakWY5x.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerZakWY5x\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerZakWY5x\App_KernelProdContainer([
    'container.build_hash' => 'ZakWY5x',
    'container.build_id' => '86ccaa87',
    'container.build_time' => 1624828882,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZakWY5x');
