<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRMJPLEC\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRMJPLEC/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerRMJPLEC.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerRMJPLEC\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerRMJPLEC\App_KernelProdContainer([
    'container.build_hash' => 'RMJPLEC',
    'container.build_id' => '42e55c19',
    'container.build_time' => 1618734500,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRMJPLEC');
