<?php

namespace ContainerRMJPLEC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GFYxa9AService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.gFYxa9A' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gFYxa9A'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'job' => ['privates', '.errored..service_locator.gFYxa9A.App\\Entity\\Job', NULL, 'Cannot autowire service ".service_locator.gFYxa9A": it references class "App\\Entity\\Job" but no such service exists.'],
            'jobPostulerRepository' => ['privates', 'App\\Repository\\JobPostulerRepository', 'getJobPostulerRepositoryService', true],
        ], [
            'entityManager' => '?',
            'job' => 'App\\Entity\\Job',
            'jobPostulerRepository' => 'App\\Repository\\JobPostulerRepository',
        ]);
    }
}
