<?php

namespace ContainerRMJPLEC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCandidatEvaluationRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\CandidatEvaluationRepository' shared autowired service.
     *
     * @return \App\Repository\CandidatEvaluationRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\CandidatEvaluationRepository'] = new \App\Repository\CandidatEvaluationRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
