<?php

namespace ContainerRMJPLEC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJobPositionRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\JobPositionRepository' shared autowired service.
     *
     * @return \App\Repository\JobPositionRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\JobPositionRepository'] = new \App\Repository\JobPositionRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
