<?php

namespace ContainerRMJPLEC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJobPostulerRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\JobPostulerRepository' shared autowired service.
     *
     * @return \App\Repository\JobPostulerRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\JobPostulerRepository'] = new \App\Repository\JobPostulerRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
