<?php

namespace ContainerZakWY5x;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DsvvdXFService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.DsvvdXF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DsvvdXF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'recruteur' => ['privates', '.errored..service_locator.DsvvdXF.App\\Entity\\Recruteur', NULL, 'Cannot autowire service ".service_locator.DsvvdXF": it references class "App\\Entity\\Recruteur" but no such service exists.'],
        ], [
            'recruteur' => 'App\\Entity\\Recruteur',
        ]);
    }
}
