<?php

namespace ContainerZakWY5x;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCandidatProfilTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\CandidatProfilType' shared autowired service.
     *
     * @return \App\Form\CandidatProfilType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\CandidatProfilType'] = new \App\Form\CandidatProfilType();
    }
}
