<?php

namespace ContainerZakWY5x;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJobCategoryRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\JobCategoryRepository' shared autowired service.
     *
     * @return \App\Repository\JobCategoryRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\JobCategoryRepository'] = new \App\Repository\JobCategoryRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
