<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSwUxFJy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSwUxFJy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSwUxFJy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSwUxFJy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSwUxFJy\App_KernelDevDebugContainer([
    'container.build_hash' => 'SwUxFJy',
    'container.build_id' => '8d19c93d',
    'container.build_time' => 1624715536,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSwUxFJy');
